### ISSUE TITLE
demo编译报错

### ISSUE THREAD

**Issue by fish2018** [gooid/gooid#2]
WallPaperTwinkle admin$ go mod init main
WallPaperTwinkle admin$ go build -buildmode c-shared -o basic/lib/armeabi/libWallPaperTwinkle.so
go: finding github.com/gooid/gooid latest
build main: cannot load github.com/gooid/gooid/internal/callfn: no Go source files

文件是存在的
WallPaperTwinkle admin$ go build
build main: cannot load github.com/gooid/gooid/internal/callfn: no Go source files
WallPaperTwinkle admin$ ls $GOPATH/src/github.com/gooid/gooid/internal/callfn
callfn.go	callfn_386.s	callfn_amd64.s	callfn_arm.s	callfn_arm64.s

**Comment by gooid** [comment]
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?



### What operating system and processor architecture are you using (`go env`)?

<pre>
$ go env

</pre>

### 另外请[参考基本编译环境](https://github.com/gooid/gooid/wiki/%E5%9F%BA%E6%9C%AC%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83)

**Comment by fish2018** [comment]
go 1.12版本

**Comment by gooid** [comment]
仅就上面的错误来说，对linux 系统请先： export GOOS=android
再次建议[参考基本编译环境](https://github.com/gooid/gooid/wiki/%E5%9F%BA%E6%9C%AC%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83)。
请先按环境做好相应配置，
这个问题先关闭，如果做好配置后有具体问题，请再提bug。
