### ISSUE TITLE
如何获取当前运行应用的签名信息

### ISSUE THREAD

**Issue by shiguanghuxian** [gooid/gooid#4]
类似下边代码功能
`public String getSHA1Signature(Context context) {
    try {
        PackageInfo info = context.getPackageManager().getPackageInfo(context.getPackageName(), PackageManager.GET_SIGNATURES);

        byte[] cert = info.signatures[0].toByteArray();

        MessageDigest md = MessageDigest.getInstance("SHA1");
        byte[] publicKey = md.digest(cert);
        StringBuilder hexString = new StringBuilder();
        for (int i = 0; i < publicKey.length; i++) {
            String appendString = Integer.toHexString(0xFF & publicKey[i])
                    .toUpperCase(Locale.US);
            if (appendString.length() == 1)
                hexString.append("0");
            hexString.append(appendString);
            hexString.append(":");
        }
        return hexString.toString();
    } catch (PackageManager.NameNotFoundException e) {
        e.printStackTrace();
    } catch (NoSuchAlgorithmException e) {
        e.printStackTrace();
    }
    return null;
}`

**Comment by gooid** [comment]
有两个方法可供参考:
1.用 go 调用 java 的方式，可参考 gomobile 中的一些做法
2.通过 package name 找到原始apk的位置(/data/app/...),然后解析apk里的签名密钥*.RSA得到签名信息

**Comment by shiguanghuxian** [comment]
好的，我试试，谢谢🙏
